-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/EImage/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ei_cache (
  ei_id SERIAL NOT NULL,
  ei_eid TEXT DEFAULT '' NOT NULL,
  ei_file TEXT DEFAULT NULL,
  ei_origin_exif TEXT DEFAULT NULL,
  ei_counter INT DEFAULT 0 NOT NULL,
  ei_width INT DEFAULT 0 NOT NULL,
  ei_height INT DEFAULT 0 NOT NULL,
  ei_actor BIGINT DEFAULT 0 NOT NULL,
  ei_ctime TIMESTAMPTZ NOT NULL,
  ei_expire TIMESTAMPTZ NOT NULL,
  ei_type SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(ei_id)
);

CREATE INDEX ei_expire_time ON ei_cache (ei_expire);

CREATE INDEX ei_eid_create ON ei_cache (ei_eid, ei_ctime);

CREATE INDEX ei_eid_expire ON ei_cache (ei_eid, ei_expire);
