-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/EImage/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ei_cache (
  ei_id SERIAL NOT NULL,
  ei_eid TEXT NOT NULL,
  ei_clip TEXT DEFAULT NULL,
  ei_file TEXT DEFAULT NULL,
  ei_origin_exif TEXT DEFAULT NULL,
  ei_counter INT DEFAULT 0 NOT NULL,
  ei_width INT DEFAULT 0 NOT NULL,
  ei_height INT DEFAULT 0 NOT NULL,
  ei_ctime TIMESTAMPTZ NOT NULL,
  ei_expire TIMESTAMPTZ NOT NULL,
  ei_type SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(ei_id)
);

CREATE INDEX ei_expire_time ON ei_cache (ei_expire);

CREATE UNIQUE INDEX ei_eid_create ON ei_cache (ei_eid, ei_file);


CREATE TABLE ei_pages (
  ei_page INT NOT NULL, ei_image TEXT NOT NULL
);

CREATE UNIQUE INDEX ei_page_image ON ei_pages (ei_page, ei_image);
